### ISSUE TITLE
Download link on demo page broken

### ISSUE THREAD

**Issue by iotaweb** [ractivejs/ractive-transitions-fade#12]
The download link at the top of the following page is broken (not found):

http://ractivejs.github.io/ractive-transitions-fade/

It currently points to:

https://raw.github.com/ractivejs/ractive-transitions-fade/master/dist/ractive-transitions-fade.js

...whereas I think it should point here:

https://raw.github.com/ractivejs/ractive-transitions-fade/master/src/ractive-transitions-fade.js

**Comment by andreujuanc** [comment]
I was about to post the same. 
Almost a year and still no fix.

**Comment by fskreuz** [comment]
@andreujuanc fixed 😄
