### ISSUE TITLE
Weird stuff going on here

### ISSUE THREAD

**Issue by JonDum** [ractivejs/ractive-transitions-fade#7]
Why are there two duplicate files?

src/Ractive-transitions-fade.js
src/ractive-transitions-fade.js

Also, this is straight up not true:

	Or, if you're using a module loader, require this module:
	    // requiring the plugin will 'activate' it - no need to use
	    // the return value
	    require( 'ractive-transitions-fade' );

Needs to say

Ractive.transitions.fade = require('ractive-transitions-fade')

Let me know if this isn't intentional and I'll clean it up for you and submit a PR.

**Comment by Rich-Harris** [comment]
D'oh, I messed this up - the version on npm (0.2.0) doesn't self-register, but the old version did (discussion [here](https://groups.google.com/forum/#!topic/ractive-js/HwDxpGak3ic), am in the process of moving plugins over to the non-self-registering browserify-friendly model). Somehow I forgot to merge the [edge branch](https://github.com/ractivejs/ractive-transitions-fade/tree/edge) into master, so the README is all out of date. Will fix. Thanks!

**Comment by JonDum** [comment]
Haha awesome man, something was definitely fishy :D
